### ISSUE TITLE
`converter.rs`

### ISSUE THREAD

**Issue by FL33TW00D** [FL33TW00D/ratchet#101]
We need a file, `converter.rs` in `ratchet_loader` that is capable of consuming GGML models and converting them into our format.

**Comment by Huguet57** [comment]
What's the difference with [ggml.rs](https://github.com/FL33TW00D/ratchet/blob/master/crates/ratchet-loader/src/ggml.rs)?

Or do you actually want to save the models in "ratchet format" in memory?

**Comment by FL33TW00D** [comment]
@Huguet57 We need to convert from GGML to Ratchets custom formatting.
Most of this is completed on #103
