### ISSUE TITLE
Quantized embeddings

### ISSUE THREAD

**Issue by FL33TW00D** [FL33TW00D/ratchet#102]
`index_write` and `nn.Embedding` need to support quantized weights.

**Comment by Huguet57** [comment]
What's the difference with [ggml.rs](https://github.com/FL33TW00D/ratchet/blob/master/crates/ratchet-loader/src/ggml.rs)?

Or do you actually want to save the models in "ratchet format" in memory?

**Comment by FL33TW00D** [comment]
Shipped in #103
