### ISSUE TITLE
Large v3 404 (in HF demo)

### ISSUE THREAD

**Issue by Huguet57** [FL33TW00D/ratchet#110]
<img width="1441" alt="Captura de pantalla 2024-03-04 a les 23 19 37" src="https://github.com/FL33TW00D/ratchet/assets/6130834/f1431c83-168c-470c-ab28-32bc4aa81c7c">

Whisper Large v3 returns 404! All the others work

**Comment by FL33TW00D** [comment]
Thanks for raising @Huguet57 V3 isn't quite ready yet!
