### ISSUE TITLE
Firefox Support 

### ISSUE THREAD

**Issue by iSuslov** [FL33TW00D/ratchet#130]
Firefox claims to support WebGPU with `dom.webgpu.enabled` flag on. In Firefox Nightly WebGPU is enabled by default. I tried both and get the same error:

> panicked at /Users/fleetwood/Code/ratchet/crates/ratchet-core/src/gpu/device.rs:113:14:
> called `Option::unwrap()` on a `None` value
> 
> Stack:
> 
> 7313/G/t.wbg.__wbg_new_abda76e883ba8a5f@https://fl33tw00d-hf-ratchet-whisper.static.hf.space/_next/static/chunks/102-57ce5954f61a9f39.js:1:15464
> @https://cdn-lfs-us-1.huggingface.co/repos/27/67/2767d538e4896c6848d48b556ef300ef30bc564fb55341e543db8568a79a2dc3/857f914139d2378bf4c50362d0319ceb8050c14550da11153f3146fa6bfb8eb2?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27ratchet-web_bg.6187fd97.wasm%3B+filename%3D%22ratchet-web_bg.6187fd97.wasm%22%3B&response-content-type=application%2Fwasm&Expires=1711258215&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMTI1ODIxNX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzI3LzY3LzI3NjdkNTM4ZTQ4OTZjNjg0OGQ0OGI1NTZlZjMwMGVmMzBiYzU2NGZiNTUzNDFlNTQzZGI4NTY4YTc5YTJkYzMvODU3ZjkxNDEzOWQyMzc4YmY0YzUwMzYyZDAzMTljZWI4MDUwYzE0NTUwZ…
> [726-aa4ed113a56a70f4.js:1:3771](https://fl33tw00d-hf-ratchet-whisper.static.hf.space/_next/static/chunks/726-aa4ed113a56a70f4.js)
> Uncaught RuntimeError: unreachable executed

Maybe this is something that could be fixed easily.

**Comment by FL33TW00D** [comment]
@iSuslov 

Just tested in FF Nightly 124 on the demo:
<img width="1280" alt="image" src="https://github.com/FL33TW00D/ratchet/assets/45471420/52f3718b-bf2b-4b9d-8aee-bfce020699d8">

Seems to work OK, could you give any more details?

I will fix that error message now.

**Comment by iSuslov** [comment]
@FL33TW00D Tried on multiple devices. 
Apple M1 Pro 16 GB
MacOS 14.4 (23E214)
Firefox Nightly 126.0a1 (2024-03-21) (64-bit)

Loading the website (all warnings):

> Feature Policy: Skipping unsupported feature name “accelerometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “ambient-light-sensor”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “autoplay”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “battery”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-read”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-write”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “document-domain”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “encrypted-media”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “gyroscope”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “layout-animations”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “legacy-image-formats”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “magnetometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “midi”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “oversized-images”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “payment”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “picture-in-picture”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “sync-xhr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “usb”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “vr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “wake-lock”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “accelerometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “ambient-light-sensor”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “autoplay”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “battery”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-read”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-write”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “document-domain”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “encrypted-media”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “gyroscope”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “layout-animations”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “legacy-image-formats”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “magnetometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “midi”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “oversized-images”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “payment”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “picture-in-picture”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “sync-xhr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “usb”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “vr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “wake-lock”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “accelerometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “ambient-light-sensor”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “autoplay”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “battery”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-read”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “clipboard-write”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “document-domain”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “encrypted-media”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “gyroscope”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “layout-animations”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “legacy-image-formats”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “magnetometer”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “midi”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “oversized-images”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “payment”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “picture-in-picture”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “sync-xhr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “usb”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “vr”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “wake-lock”. ratchet-whisper
> Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. ratchet-whisper
> This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. index.html
> Partitioned cookie or storage access was provided to “https://fl33tw00d-hf-ratchet-whisper.static.hf.space/index.html” because it is loaded in the third-party context and dynamic state partitioning is enabled.
> Some cookies are misusing the recommended “SameSite“ attribute 18
> The resource at “<URL>” was blocked because content blocking is enabled. 2
> WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. challenge.js:2:157091
> Request to access cookie or storage on “https://js.stripe.com/v3/m-outer-3437aaddcdf6922d623e172c2d6f9278.html#url=https%3A%2F%2Fhuggingface.co%2Fspaces%2FFL33TW00D-HF%2Fratchet-whisper&title=Ratchet%20%2B%20Whisper%20-%20a%20Hugging%20Face%20Space%20by%20FL33TW00D-HF&referrer=&muid=NA&sid=NA&version=6&preview=false” was blocked because it came from a tracker and content blocking is enabled.
> Partitioned cookie or storage access was provided to “https://m.stripe.network/inner.html#url=https%3A%2F%2Fhuggingface.co%2Fspaces%2FFL33TW00D-HF%2Fratchet-whisper&title=Ratchet%20%2B%20Whisper%20-%20a%20Hugging%20Face%20Space%20by%20FL33TW00D-HF&referrer=&muid=NA&sid=NA&version=6&preview=false” because it is loaded in the third-party context and dynamic state partitioning is enabled.
> Request to access cookie or storage on “https://m.stripe.com/6” was blocked because it came from a tracker and content blocking is enabled.
> 

Loading `Tiny Model`

> WARN crates/ratchet-web/src/model.rs:90 
> [2024-03-22][02:28:36][ratchet_web::model][WARN] Loading model: WhisperTiny Q8 102-57ce5954f61a9f39.js:1:34655
> WARN crates/ratchet-web/src/model.rs:97 
> [2024-03-22][02:28:36][ratchet_web::model][WARN] Loading model: ModelKey { repo_id: "FL33TW00D-HF/whisper-tiny", model_id: "tiny_q8.bin" } 102-57ce5954f61a9f39.js:1:34655
> WARN crates/ratchet-web/src/model.rs:102 
> [2024-03-22][02:28:36][ratchet_web::model][WARN] Model not found in db, fetching from remote 102-57ce5954f61a9f39.js:1:34655
> panicked at /Users/fleetwood/Code/ratchet/crates/ratchet-core/src/gpu/device.rs:113:14:
> called `Option::unwrap()` on a `None` value
> 
> Stack:
> 
> 7313/G/t.wbg.__wbg_new_abda76e883ba8a5f@https://fl33tw00d-hf-ratchet-whisper.static.hf.space/_next/static/chunks/102-57ce5954f61a9f39.js:1:15464
> @https://cdn-lfs-us-1.huggingface.co/repos/27/67/2767d538e4896c6848d48b556ef300ef30bc564fb55341e543db8568a79a2dc3/857f914139d2378bf4c50362d0319ceb8050c14550da11153f3146fa6bfb8eb2?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27ratchet-web_bg.6187fd97.wasm%3B+filename%3D%22ratchet-web_bg.6187fd97.wasm%22%3B&response-content-type=application%2Fwasm&Expires=1711348013&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMTM0ODAxM319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzI3LzY3LzI3NjdkNTM4ZTQ4OTZjNjg0OGQ0OGI1NTZlZjMwMGVmMzBiYzU2NGZiNTUzNDFlNTQzZGI4NTY4YTc5YTJkYzMvODU3ZjkxNDEzOWQyMzc4YmY0YzUwMzYyZDAzMTljZWI4MDUwYzE0NTUwZ…
> 726-aa4ed113a56a70f4.js:1:3771
> Uncaught RuntimeError: unreachable executed
> 857f914139d2378bf4c50362d0319ceb8050c14550da11153f3146fa6bfb8eb2:1797616:1

Does it somehow have to do with this path `/Users/fleetwood/Code/ratchet/crates/ratchet-core/src/gpu/device.rs`?


<img width="1542" alt="Screenshot 2024-03-22 at 2 31 13 AM" src="https://github.com/FL33TW00D/ratchet/assets/7628774/d3354836-d46e-4a00-9021-8f8427c8b21b">

**Comment by FL33TW00D** [comment]
Hi @iSuslov,
That line simply says it's unable to acquire the device (I've improved the error message already).

Have you checked how you've setup WebGPU in FF nightly?

**Comment by iSuslov** [comment]
My bad, after further investigation it turned out that I had `WebGPU is disabled by blocklist` even for Nightly build with `dom.webgpu.enabled` flag on.

> To check WebGPU status one can type `about:support` in the address bar.

To make it work I had to turn `gfx.webgpu.ignore-blocklist` flag on in `about:config`.

Thank you @FL33TW00D for your help here!

**Comment by FL33TW00D** [comment]
I think this will be a frequently raised issue, thank you for raising! 

Maybe we need a `PLATFORMS.md` or something with a guide for each OS & browser.

I'll also make the error message much more informative.
