### ISSUE TITLE
Port hf-hub for wasm-usage

### ISSUE THREAD

**Issue by sigma-andex** [FL33TW00D/ratchet#15]
Correct me if I'm wrong, but from my understanding `hf-hub` currently wouldn't work in the browser. We could create a PR to add support, though I'm not sure if that makes a lot of sense. Some thoughts:
- hf-hub currently uses ureq (online) and reqwest (tokio), ureq doesn't seem to support wasm, while reqwest does. Though we could also use plain fetch requests
- hf-hub is currently thought for console based usage and uses indicatif for the progress bar. I checked and indicatif seems to work in wasm, though that is probably not what you want in this use-case. You'd probably want to show a progress-bar in the browser to the user rather than in the web console, so that would probably require a change in the api.
- we'll want to use the [Cache Web API](https://developer.mozilla.org/en-US/docs/Web/API/Cache)

**Comment by FL33TW00D** [comment]
https://rustwasm.github.io/docs/wasm-bindgen/examples/fetch.html
https://github.com/emilk/ehttp

**Comment by FL33TW00D** [comment]
We have a decent start on this
