### ISSUE TITLE
Whisper example

### ISSUE THREAD

**Issue by Huguet57** [FL33TW00D/ratchet#88]
Hi,
Now that tests work, the next step I am searching for is a Whisper-on-the-web example.

GPT tells me it should be done like:

```sh
wasm-pack build --target web
```

Having a `index.html` like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WASM App</title>
</head>
<body>
    <h1>WASM App</h1>
    <script type="module">
        import init from './pkg/whisper_example.js';

        async function loadWasm() {
            await init();
            // After this, you can call exported Rust functions
        }

        loadWasm().catch(console.error);
    </script>
</body>
</html>
```

And serving it via:

```sh
http-server
```

It can be the adapted code of the `whisper.rs` file, I am trying to turn it into a library. How easy would that be?

**Comment by FL33TW00D** [comment]
@Huguet57 It's not quite ready yet, I'll be happy to make an example in the coming week!
